spring:
  application:
    name: gateway-web
server:
  port: 9011
  redis:
    host: 192.168.0.120
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors‐configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #唯一标识符
        - id: shopping_goods_route
          #uri: http://localhost:18081
          #5。负载均衡
          uri: lb://goods
          #断言，配置路由的规则配置
          predicates:
            #1。Host过滤
            #所有以cloud.bluesky.com的请求，都会路由到http://localhost:18081
            #- Host=cloud.bluesky.com**
            #2。path路径过滤
            #所有以/brand开始的请求，都路由http://localhost:18081微服务，例如：localhost:8001/brand/1912会路由到http://localhost:18081/brand/1912
            #- Path=/api/brand/**
            #4.添加前缀,所有的请求，帮你加个前缀,见下面PrefixPath=/brand
            - Path=/**
          #3。去掉前缀
          #所有以/api/brand的请求，都被路由到http://localhost:18081微服务
          #希望该路径由微服务网关自动把/api去掉
          filters:
            #将请求路径中的第一个路径去掉，请求路径以/区分，一个/代表一级路级
            #- StripPrefix=1
            #4。添加前缀
            #- PrefixPath=/brand
            #6。请求数限流
            - name: RequestRateLimiter #请求速率限制器 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"   #用户请求身份唯一标识符
                redis-rate-limiter.replenishRate: 10 #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 10 #令牌桶总容量，允许并发请求个数
        - id: shopping_user_route
          uri: lb://user  #下面这些请求开始的请求，给user服务
          predicates: #路由断言，规则配置
            - Path=/address/**,/areas/**,/cities/**,/user/**,/provinces/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

