server:
  port: 9001

spring:
  application:
    name: gateway-system
  redis:
    host: 192.168.0.120
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors‐configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
      - id: shopping-system-route
        uri: lb://system
        predicates: #断言
          #所有访问网关路由下面这个路径的,转发到lb://system微服务
          - Path=/system/**
        filters:
          - StripPrefix= 1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

